# Configuration for https://goreleaser.com/
project_name: authenticator

builds:
  - id: aws-iam-authenticator
    binary: aws-iam-authenticator
    main: ./cmd/aws-iam-authenticator/
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      # Windows arm64 is not used and does not compile well as of writing
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X pkg.Version={{.Version}} -X pkg.CommitID={{.Commit}} -buildid=''"

snapshot:
  name_template: "git-{{.ShortCommit}}"

archives:
  - id: bin
    format: binary

release:
  draft: true
  prerelease: false
  name_template: "v{{.Version}}"
